# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

# Bump macOS images to a new one because waiting for Homebrew to
# install an acceptable version of Ruby is horrible
osx_image: xcode9.1

env:
  global:
    - CRATE_NAME: omnishock
    - LD_LIBRARY_PATH: /usr/local/lib

matrix:
  include:
    # macOS
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: 1.32.0

    # macOS (Stable)
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable

    # macOS (Beta)
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: beta

    # No Linux builds until https://github.com/japaric/cross/issues/149 is fixed
    # # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: 1.32.0
    # - env: TARGET=armv7-unknown-linux-gnueabihf
    #   rust: 1.32.0

    # # Linux (Stable)
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: stable
    # - env: TARGET=armv7-unknown-linux-gnueabihf
    #   rust: stable

    # # Linux (Beta)
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: beta
    # - env: TARGET=armv7-unknown-linux-gnueabihf
    #   rust: beta

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

before_script:
  - rustup component add rustfmt

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: suObohesbwTyDQDpj1FHKE0FisgjFlHeYk8k+enqo3mPPqGmhdqURScsHwum6NUQtvhLH2e2BHvGEwqyydAvp9NOzb5lNbFcsJNN13X9SI0fdKp31y78BUZpBcGl/0ElUp3s6Y3nSJ789NDyIrAhUhCYcav9fRF4glTzZpyU9FMAlMlPaJiwQ8GhHPk5nQCcHiBdqBHi+gJUAtSDIhFLvZsK2Yex6x3hbyI3vxTLwop0PhGu2nx9+36xaoV6RVo0At8j4dANAtKC1r4Iqxr4yHnVDcVGu3aKsUueWOdcNi01h95hqISqAcc0COE8ei2IHGbdk3VSDOqhTH19NgEjXlTt7JoH4rmMUbA30JR/j4o4rQJh2WXUO5oBwYJIfddSENS11ue0R2/R76ngjgm2RWpbexNIow8ehu2MLOGeTB80XetpAuY2pwVcFct0jEx2HsJAVEX21w4K6jp2YQLemhtdh3rKsYyqiZLwVAMeB7irdPVx9oho4AZkgqNXV1kLZ0eKy5Xm+F+KQ04f7BUdUbLdshVb8YFPISx9QFuFORJBWxOUJDoDeoQGIZVZArxZFVmeSQhX59baQNYT+TNjDOrOXDQeRw4s4jaDT57fn15Ynik0pMRlz+AUfECplxtTYMwVahnNjR2XLmDSVATIu4fuQ+Ie95teYolChPL4kus=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = 1.32.0
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - develop
