language: rust
cache: cargo
rust:
  - 1.19.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
install:
  - wget https://www.libsdl.org/release/SDL2-2.0.6.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-* && ./configure --disable-audio --disable-video --disable-render --disable-power && make && sudo make install && popd
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
