[package]
name = "omnishock"
version = "0.0.6"
description = "Something to do with game controllers!"
authors = [ "Jessica Stokes <hello@jessicastokes.net>" ]
repository = "https://github.com/ticky/omnishock.git"
homepage = "https://github.com/ticky/omnishock"
license = "MIT"
readme = "README.md"

[dependencies]
clap = "2.26.2"
hex-view = "0.1.1"
sdl2 = "0.30.0"
serial = "0.4"

[target.x86_64-unknown-linux-gnu]
image = "sdl2-x86_64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "sdl2-armv7-unknown-linux-gnueabihf"
