[package]
name = "omnishock"
version = "0.0.3"
description = "Something to do with game controllers!"
authors = [ "Jessica Stokes <hello@jessicastokes.net>" ]
repository = "https://github.com/ticky/omnishock.git"
homepage = "https://github.com/ticky/omnishock"
license = "MIT"
readme = "README.md"

[dependencies]
clap = "2.20.0"
sdl2 = "0.27.2"
serial = "0.4"
