[target.arm-unknown-linux-gnueabihf]
rustflags = [
    "-L", "/usr/lib/arm-linux-gnueabihf",
    "-C", "link-args=-Wl,-rpath-link=/usr/lib/arm-linux-gnueabihf,-rpath-link=/lib/arm-linux-gnueabihf,-rpath-link=/usr/lib/arm-linux-gnueabihf/pulseaudio,-rpath-link=/raspberrypi/rootfs/opt/vc/lib",
]