[target.arm-unknown-linux-gnueabihf]
rustflags = [
    "-L", "/opt/raspberrypi/rootfs/usr/lib/arm-linux-gnueabihf",
    "-C", "link-args=-Wl,-rpath-link=/opt/raspberrypi/rootfs/usr/lib/arm-linux-gnueabihf,-rpath-link=/opt/raspberrypi/rootfs/lib/arm-linux-gnueabihf,-rpath-link=/opt/raspberrypi/rootfs/usr/lib/arm-linux-gnueabihf/pulseaudio,-rpath-link=/opt/raspberrypi/rootfs/opt/vc/lib/",
]